from __future__ import annotations

from src.schema import Problem, Step


def S(*pairs: tuple[str, str]) -> list[Step]:
    return [Step(title=t, text=x) for t, x in pairs]


def P(**kwargs) -> Problem:
    problem = Problem(**kwargs)
    problem.validate()
    return problem


DIAGNOSTIC_PROBLEMS: list[Problem] = [
    P(
        id="diag-1-1",
        skill_id="alg-1-1",
        stage=1,
        cluster="foundations",
        prompt="Evaluate.\n\n$6 + 2 \\cdot 3^2 - 8 \\div 4$",
        answer="22",
        answer_display="22",
        hint="Exponents, then multiply and divide left to right, then add and subtract left to right.",
        common_mistakes=["Doing 6+2 first, or treating 3^2 as 6."],
        exam_tags=["clep_algebra"],
        steps=S(
            ("Goal", "This is not an equation. We want one number. The order of operations is a shared convention so everyone gets the same value."),
            ("Exponents", "3^2 = 9. The expression is now 6 + 2 · 9 - 8 ÷ 4."),
            ("Multiply and divide, left to right", "2 · 9 = 18 and 8 ÷ 4 = 2. Now we have 6 + 18 - 2."),
            ("Add and subtract, left to right", "6 + 18 = 24, then 24 - 2 = 22."),
        ),
    ),
    P(
        id="diag-1-2",
        skill_id="alg-1-2",
        stage=1,
        cluster="foundations",
        prompt="Simplify to an integer.\n\n$\\dfrac{2^7}{2^3}$",
        answer="16",
        answer_display="16",
        hint="Same base in a quotient: subtract exponents, then evaluate.",
        common_mistakes=["Dividing the exponents (7/3) or subtracting the bases."],
        exam_tags=["clep_algebra"],
        steps=S(
            ("Goal", "Collapse a quotient of powers into a single power of 2, then evaluate."),
            ("Quotient rule", "2^7 / 2^3 = 2^{7-3} = 2^4, because you cancel three factors of 2 from seven factors of 2."),
            ("Evaluate", "2^4 = 16. That is the fully simplified integer value."),
            ("Check by expanding", "2^7 = 128 and 2^3 = 8, and 128/8 = 16. Same answer, slower."),
        ),
    ),
    P(
        id="diag-1-3",
        skill_id="alg-1-3",
        stage=1,
        cluster="foundations",
        prompt="Simplify.\n\n$\\sqrt{72}$",
        answer="6*sqrt(2)",
        answer_display="6√2",
        hint="Factor out the largest perfect square inside the radical.",
        common_mistakes=["Writing √72 as √7 · √2, or reducing 72 to 8√9 incorrectly."],
        exam_tags=["clep_algebra"],
        steps=S(
            ("Goal", "A simplified square root has no perfect-square factor left under the radical."),
            ("Factor", "72 = 36 · 2, and 36 = 6^2 is the largest perfect square factor of 72."),
            ("Split", "√72 = √(36 · 2) = √36 · √2 = 6√2."),
            ("Why not √36 + √2", "Roots do not split over addition. They do split over multiplication, which is what we used."),
        ),
    ),
    P(
        id="diag-1-4",
        skill_id="alg-1-5",
        stage=1,
        cluster="foundations",
        prompt="Factor completely.\n\n$x^2 - 5x - 14$",
        answer="(x-7)*(x+2)",
        answer_display="(x-7)(x+2)",
        hint="Two numbers that multiply to -14 and add to -5.",
        common_mistakes=["(x-7)(x-2), which would give a positive middle term of the wrong size."],
        exam_tags=["clep_algebra"],
        steps=S(
            ("Goal", "Rewrite the trinomial as a product of binomials."),
            ("What we need", "Integers m, n with m·n = -14 and m+n = -5. The product is negative, so the two numbers have opposite signs, and the more negative one has larger absolute value because the sum is negative."),
            ("The pair", "-7 and +2: (-7)(2) = -14 and -7+2 = -5."),
            ("Write and FOIL-check", "(x-7)(x+2) = x^2 + 2x - 7x - 14 = x^2 - 5x - 14. Matches."),
        ),
    ),
    P(
        id="diag-1-5",
        skill_id="alg-1-6",
        stage=1,
        cluster="foundations",
        prompt="Simplify.\n\n$\\dfrac{x^2 - 9}{x^2 + 5x + 6}$",
        answer="(x-3)/(x+2)",
        answer_display="(x-3)/(x+2)",
        hint="Factor numerator and denominator, then cancel a common factor. Remember excluded values.",
        common_mistakes=["Canceling the x^2 terms and writing -9/(5x+6). You cannot cancel terms of a sum."],
        exam_tags=["clep_algebra"],
        steps=S(
            ("Goal", "Simplify a rational expression by canceling shared factors."),
            ("Factor", "Numerator is a difference of squares: x^2 - 9 = (x-3)(x+3). Denominator: numbers that multiply to 6 and add to 5 are 2 and 3, so (x+2)(x+3)."),
            ("Cancel", "(x-3)(x+3) / ((x+2)(x+3)) = (x-3)/(x+2), provided x ≠ -3 (and also x ≠ -2 from the leftover denominator)."),
            ("Excluded values stay", "Even after canceling, x = -3 was a hole in the original expression, and x = -2 is still undefined."),
        ),
    ),
    P(
        id="diag-1-6",
        skill_id="alg-2-2",
        stage=1,
        cluster="foundations",
        prompt="Solve for $x$.\n\n$3(x - 4) = 2x + 5$",
        answer="17",
        answer_display="17",
        hint="Distribute first, then collect x-terms on one side and constants on the other.",
        common_mistakes=["Distributing 3 only onto x, leaving -4, or subtracting 2x from only one side."],
        exam_tags=["clep_algebra"],
        steps=S(
            ("Goal", "Find the unique x that makes both sides equal."),
            ("Distribute", "3(x-4) = 3x - 12. Equation: 3x - 12 = 2x + 5."),
            ("Collect x-terms", "Subtract 2x from both sides: x - 12 = 5. Add 12 to both sides: x = 17."),
            ("Check", "Left: 3(17-4) = 3(13) = 39. Right: 2(17)+5 = 34+5 = 39. Equal, so x = 17 is correct."),
        ),
    ),
    P(
        id="diag-1-7",
        skill_id="alg-2-5",
        stage=1,
        cluster="foundations",
        prompt="Solve. List both solutions.\n\n$x^2 - 2x - 15 = 0$",
        answer="-3, 5",
        answer_display="-3, 5",
        hint="Factor, then set each factor equal to 0.",
        common_mistakes=["Reporting 3 and -5, the opposite signs of the actual roots."],
        exam_tags=["clep_algebra"],
        steps=S(
            ("Goal", "A quadratic can have two real solutions. We want both."),
            ("Factor", "Numbers that multiply to -15 and add to -2: -5 and 3. Wait — (-5)+3 = -2 and (-5)(3) = -15. So (x-5)(x+3) = 0? FOIL: x^2 +3x -5x -15 = x^2 -2x -15. Yes, (x-5)(x+3)=0."),
            ("Zero product", "x-5 = 0 or x+3 = 0, so x = 5 or x = -3."),
            ("Check one", "x=5: 25 - 10 - 15 = 0. x=-3: 9 + 6 - 15 = 0. Both work."),
        ),
    ),
    P(
        id="diag-1-8",
        skill_id="alg-2-7",
        stage=1,
        cluster="foundations",
        prompt="Solve. Write your answer like x>2 or x<=-1.\n\n$-2x + 6 < 10$",
        answer="x>-2",
        answer_display="x > -2",
        hint="Isolate x, and reverse the inequality when you divide by a negative number.",
        common_mistakes=["Leaving the inequality as x < -2 because you did not flip after dividing by -2."],
        exam_tags=["clep_algebra"],
        steps=S(
            ("Goal", "Find every x that makes the inequality true."),
            ("Undo addition", "Subtract 6 from both sides: -2x < 4."),
            ("Divide by a negative", "Divide by -2 and reverse <: x > -2."),
            ("Check a point", "Try x = 0, which is greater than -2: -2(0)+6 = 6 < 10, true. Try x = -3: -2(-3)+6 = 12, and 12 < 10 is false. The direction is right."),
        ),
    ),
    P(
        id="diag-2-1",
        skill_id="alg-3-1",
        stage=2,
        cluster="functions",
        prompt="If $f(x) = 2x^2 - 3x + 1$, find $f(-2)$.",
        answer="15",
        answer_display="15",
        hint="Replace every x with -2, using parentheses around the negative input.",
        common_mistakes=["Computing 2(-2)^2 as (-4)^2, or dropping the sign on -3x."],
        exam_tags=["clep_algebra", "ap_precalc_u1"],
        steps=S(
            ("Goal", "Evaluating a function means substituting the given input into the formula."),
            ("Substitute", "f(-2) = 2(-2)^2 - 3(-2) + 1. The parentheses around -2 are doing real work."),
            ("Powers first", "(-2)^2 = 4, so 2·4 = 8. Then -3(-2) = +6."),
            ("Add", "8 + 6 + 1 = 15. Use the signed middle term carefully: minus a negative became plus."),
        ),
    ),
    P(
        id="diag-2-2",
        skill_id="alg-3-2",
        stage=2,
        cluster="functions",
        prompt="Find the excluded x-value (the number not in the domain) of $f(x) = \\dfrac{x+1}{x-4}$.",
        answer="4",
        answer_display="4",
        hint="A fraction is undefined where the denominator is 0.",
        common_mistakes=["Excluding x = -1, the zero of the numerator (that is an x-intercept, and it is allowed)."],
        exam_tags=["clep_algebra", "ap_precalc_u1"],
        steps=S(
            ("Goal", "Domain is the set of legal inputs. Division by zero is illegal."),
            ("Set denominator ≠ 0", "x - 4 ≠ 0, so x ≠ 4."),
            ("Numerator zero is fine", "When x = -1, f(-1) = 0/(-5) = 0, a perfectly good output."),
            ("Domain", "All real numbers except 4, written (-∞, 4) ∪ (4, ∞). The excluded value is 4."),
        ),
    ),
    P(
        id="diag-2-3",
        skill_id="alg-3-4",
        stage=2,
        cluster="functions",
        prompt="If $f(x) = 3x+1$ and $g(x) = x^2$, find $(f \\circ g)(2)$.",
        answer="13",
        answer_display="13",
        hint="(f ∘ g)(2) = f(g(2)). Do g first.",
        common_mistakes=["Computing g(f(2)) = (7)^2 = 49 instead."],
        exam_tags=["clep_algebra", "ap_precalc_u2"],
        steps=S(
            ("Goal", "Composition is a chain: the output of g becomes the input of f."),
            ("Inner", "g(2) = 2^2 = 4. Always finish the inner function completely before touching f."),
            ("Outer", "Now feed 4 into f: f(4) = 3(4)+1 = 12+1 = 13."),
            ("Wrong-order warning", "g(f(2)) = g(7) = 49, which is a different problem. Read ∘ from right to left."),
        ),
    ),
    P(
        id="diag-2-4",
        skill_id="alg-3-5",
        stage=2,
        cluster="functions",
        prompt="Compared to $y = x^2$, the graph of $y = (x+3)^2$ is shifted how many units, and in which direction? Enter like 3 left or 3 right.",
        answer="3 left",
        answer_display="3 left",
        hint="f(x+h) with h>0 moves the graph left. Inside changes are horizontal and backwards.",
        common_mistakes=["Saying 3 right because of the plus sign."],
        exam_tags=["ap_precalc_u1"],
        steps=S(
            ("Goal", "Identify a horizontal translation of a parent graph."),
            ("Parent landmark", "y = x^2 has its vertex at (0,0)."),
            ("Inside plus", "y = (x+3)^2 = (x-(-3))^2, which is the vertex-form shift of 3 units left. The vertex is now (-3, 0)."),
            ("Memory aid", "The graph moves so that the 'new x' that makes the inside zero is x = -3. It follows the vertex, not the sign painted on the formula."),
        ),
    ),
    P(
        id="diag-2-5",
        skill_id="alg-3-7",
        stage=2,
        cluster="functions",
        prompt="Find $f^{-1}(x)$ if $f(x) = 5x - 4$. Enter an expression in x, such as (x+4)/5.",
        answer="(x+4)/5",
        answer_display="(x+4)/5",
        hint="Swap x and y, then solve for y. Inverse is not 1/f(x).",
        common_mistakes=["Writing 1/(5x-4), or (x-4)/5."],
        exam_tags=["clep_algebra", "ap_precalc_u2"],
        steps=S(
            ("Goal", "The inverse undoes f. f^{-1} is a new function, not an exponent."),
            ("Set y = 5x - 4", "Write y = 5x - 4, then swap the letters: x = 5y - 4. Swapping is the geometric idea of reflecting across y = x."),
            ("Solve for y", "x + 4 = 5y, so y = (x+4)/5."),
            ("Check", "f(f^{-1}(x)) = 5·((x+4)/5) - 4 = (x+4) - 4 = x. It undoes."),
        ),
    ),
    P(
        id="diag-2-6",
        skill_id="alg-5-1",
        stage=2,
        cluster="functions",
        prompt="Find the x-coordinate of the vertex of $y = 2x^2 - 8x + 1$.",
        answer="2",
        answer_display="2",
        hint="x = -b/(2a) for y = ax^2 + bx + c.",
        common_mistakes=["Using 8/2 = 4, or -b/a = 4."],
        exam_tags=["ap_precalc_u1"],
        steps=S(
            ("Goal", "The vertex x-coordinate is the axis of symmetry of the parabola."),
            ("Identify a and b", "In y = ax^2 + bx + c we have a = 2 and b = -8. The minus sign on 8 is part of b."),
            ("Formula", "x = -(-8) / (2·2) = 8/4 = 2."),
            ("Why it works", "Completing the square on 2x^2 - 8x would produce 2(x-2)^2 + constant, showing the same h = 2."),
        ),
    ),
    P(
        id="diag-2-7",
        skill_id="alg-6-3",
        stage=2,
        cluster="functions",
        prompt="Evaluate $\\log_2 32$.",
        answer="5",
        answer_display="5",
        hint="log_2 32 is the exponent you put on 2 to get 32.",
        common_mistakes=["Answering 16, or 2^32."],
        exam_tags=["clep_algebra", "ap_precalc_u2"],
        steps=S(
            ("Goal", "A log is an exponent."),
            ("Rewrite", "log_2 32 = c means 2^c = 32."),
            ("Powers of 2", "2^1=2, 2^2=4, 2^3=8, 2^4=16, 2^5=32. So the missing exponent is 5."),
            ("Check", "2^5 = 32, which matches the argument of the log. The value is 5."),
        ),
    ),
    P(
        id="diag-2-8",
        skill_id="alg-6-6",
        stage=2,
        cluster="functions",
        prompt="Solve for $x$.\n\n$3^{x} = 81$",
        answer="4",
        answer_display="4",
        hint="Write 81 as a power of 3, then equate exponents.",
        common_mistakes=["x = 81/3 = 27, treating the exponential as multiplication."],
        exam_tags=["clep_algebra", "ap_precalc_u2"],
        steps=S(
            ("Goal", "Solve an exponential equation by matching bases."),
            ("Rewrite 81", "81 = 3^4, because 3·3·3·3 = 81."),
            ("Equal bases", "3^x = 3^4, so x = 4 (the exponential base 3 is one-to-one)."),
            ("Check", "3^4 = 81, which matches the right-hand side, so x = 4 is correct."),
        ),
    ),
    P(
        id="diag-3-1",
        skill_id="trig-7-1",
        stage=3,
        cluster="trig",
        prompt="Convert $150^\\circ$ to radians. Enter a simplified expression in terms of pi, like 5*pi/6.",
        answer="5*pi/6",
        answer_display="5π/6",
        hint="Multiply degrees by π/180 and simplify the fraction.",
        common_mistakes=["Using 180/π, or reducing 150π/180 to 15π/18 instead of 5π/6."],
        exam_tags=["ap_precalc_u3", "clep_precalc"],
        steps=S(
            ("Goal", "Degrees and radians measure the same angle with different units. Calculus almost always uses radians."),
            ("Conversion factor", "π radians = 180°, so multiply by π/180: 150 · π/180."),
            ("Simplify", "150/180 = 15/18 = 5/6, so 5π/6."),
            ("Sanity", "150° is in quadrant II, a bit less than 180° = π. 5π/6 is a bit less than π. Matches."),
        ),
    ),
    P(
        id="diag-3-2",
        skill_id="trig-7-3",
        stage=3,
        cluster="trig",
        prompt="Find the exact value of $\\sin(2\\pi/3)$. Enter something like sqrt(3)/2.",
        answer="sqrt(3)/2",
        answer_display="√3/2",
        hint="2π/3 is 120°, a quadrant II angle whose reference angle is π/3.",
        common_mistakes=["Giving the cosine instead, or a negative sine (sine is positive in QII)."],
        exam_tags=["ap_precalc_u3", "clep_precalc"],
        steps=S(
            ("Goal", "Exact unit-circle values use reference angles and quadrant signs, not a calculator."),
            ("Where is the angle", "2π/3 = 120° sits in quadrant II. The reference angle is π - 2π/3 = π/3."),
            ("Reference value", "sin(π/3) = √3/2. Sine (the y-coordinate) is positive in quadrant II."),
            ("Conclusion", "sin(2π/3) = +√3/2. The plus sign is required because we are in quadrant II."),
        ),
    ),
    P(
        id="diag-3-3",
        skill_id="trig-7-2",
        stage=3,
        cluster="trig",
        prompt="In a right triangle, the side opposite θ is 5 and the hypotenuse is 13. Find sin θ as a fraction.",
        answer="5/13",
        answer_display="5/13",
        hint="SOH: sine = opposite / hypotenuse.",
        common_mistakes=["Using 5/12 (that's opposite/adjacent, which is tangent if the adjacent is 12)."],
        exam_tags=["ap_precalc_u3", "clep_precalc"],
        steps=S(
            ("Goal", "Right-triangle trig ratios compare two sides. Sine uses opposite and hypotenuse."),
            ("SOH-CAH-TOA", "sin θ = opposite / hypotenuse."),
            ("Plug in", "sin θ = 5/13. Leave it as a fraction; do not switch to a decimal unless asked."),
            ("Optional", "If you needed the adjacent side it would be √(13^2-5^2)=√(169-25)=√144=12, but sine does not need that."),
        ),
    ),
    P(
        id="diag-3-4",
        skill_id="trig-8-1",
        stage=3,
        cluster="trig",
        prompt="What is the period of $y = \\sin(4x)$? Enter a simplified expression like pi/2.",
        answer="pi/2",
        answer_display="π/2",
        hint="Period of sin(bx) is 2π/|b|.",
        common_mistakes=["Answering 4, or 2π·4 = 8π."],
        exam_tags=["ap_precalc_u3"],
        steps=S(
            ("Goal", "Period is how much x must increase before the graph repeats."),
            ("Parent period", "y = sin x repeats every 2π."),
            ("Horizontal stretch/compress", "Inside, x is replaced by 4x, so the graph is compressed by 4. Period = 2π/4 = π/2."),
            ("Check", "When x increases by π/2, 4x increases by 2π, a full sine cycle."),
        ),
    ),
    P(
        id="diag-3-5",
        skill_id="trig-8-3",
        stage=3,
        cluster="trig",
        prompt="Evaluate $\\arcsin(1/2)$ in radians (principal value). Enter like pi/6.",
        answer="pi/6",
        answer_display="π/6",
        hint="arcsin returns the angle in [-π/2, π/2] whose sine is the given number.",
        common_mistakes=["5π/6, which also has sine 1/2 but is not the principal value."],
        exam_tags=["ap_precalc_u3"],
        steps=S(
            ("Goal", "Inverse sine picks one specific angle, the principal value."),
            ("Which angle has sine 1/2", "sin(π/6) = 1/2, and π/6 is inside [-π/2, π/2]."),
            ("Why not 5π/6", "sin(5π/6) is also 1/2, but 5π/6 is outside the range of arcsin."),
            ("Answer", "arcsin(1/2) = π/6. That is the unique principal value."),
        ),
    ),
    P(
        id="diag-3-6",
        skill_id="trig-9-1",
        stage=3,
        cluster="trig",
        prompt="Simplify $\\dfrac{\\sin x}{\\cos x}$ to a single trig function name (like tan(x)).",
        answer="tan(x)",
        answer_display="tan(x)",
        hint="This is the definition of tangent.",
        common_mistakes=["Writing cot(x), which is cos/sin."],
        exam_tags=["ap_precalc_u3", "clep_precalc"],
        steps=S(
            ("Goal", "Rewrite a quotient of fundamental trig functions as one function."),
            ("Definition", "tan x is defined as sin x / cos x, wherever cos x ≠ 0."),
            ("Conclusion", "The simplified form is tan(x)."),
            ("Related", "The reciprocal identity is cot x = cos x / sin x, which is the other way up."),
        ),
    ),
    P(
        id="diag-3-7",
        skill_id="trig-9-5",
        stage=3,
        cluster="trig",
        prompt="How many solutions does $\\sin x = 1/2$ have in the interval $[0, 2\\pi)$? Enter an integer.",
        answer="2",
        answer_display="2",
        hint="Sine is positive in quadrants I and II. One solution per those quadrants in one full rotation.",
        common_mistakes=["Counting only π/6, or including 2π as a third solution (sine is 0 there, and 2π is not in a half-open interval starting at 0 if you already counted 0)."],
        exam_tags=["ap_precalc_u3"],
        steps=S(
            ("Goal", "Count solutions on one full rotation, not just the reference angle."),
            ("Reference angle", "sin^{-1}(1/2) = π/6."),
            ("Quadrants", "Sine is positive in Q I and Q II: x = π/6 and x = π - π/6 = 5π/6."),
            ("How many", "Exactly two solutions in [0, 2π)."),
        ),
    ),
    P(
        id="diag-3-8",
        skill_id="trig-10-1",
        stage=3,
        cluster="trig",
        prompt="A triangle has angle A = 40°, angle B = 60°, and side a = 10 (opposite A). Find angle C in degrees.",
        answer="80",
        answer_display="80",
        hint="Angles in a triangle sum to 180°. You do not need the Law of Sines yet.",
        common_mistakes=["Using 40+60=100 as the third angle."],
        exam_tags=["clep_precalc"],
        steps=S(
            ("Goal", "The third angle of any Euclidean triangle is determined by the other two."),
            ("Angle sum", "In any triangle, A + B + C = 180°. This is geometry, not the Law of Sines."),
            ("Compute", "C = 180 - 40 - 60 = 80."),
            ("Why side a was listed", "You would need a and the Law of Sines if the question asked for side b or c. For angle C, the angle sum is enough."),
        ),
    ),
    P(
        id="diag-4-1",
        skill_id="alg-11-1",
        stage=4,
        cluster="precalc",
        prompt="Solve. Enter x,y.\n\n$x + y = 7$\n\n$x - y = 1$",
        answer="4,3",
        answer_display="(4, 3)",
        hint="Add the two equations to eliminate y.",
        common_mistakes=["Getting x=3, y=4 by swapping."],
        exam_tags=["clep_algebra", "clep_precalc"],
        steps=S(
            ("Goal", "Find the ordered pair that sits on both lines."),
            ("Add", "(x+y) + (x-y) = 7+1 ⇒ 2x = 8 ⇒ x = 4."),
            ("Back-substitute", "Put x = 4 into x + y = 7: 4 + y = 7, so y = 3."),
            ("Check the second", "4 - 3 = 1. Both equations hold."),
        ),
    ),
    P(
        id="diag-4-2",
        skill_id="pc-12-1",
        stage=4,
        cluster="precalc",
        prompt="The graph of $\\dfrac{x^2}{9} + \\dfrac{y^2}{4} = 1$ is which conic? Enter ellipse, hyperbola, or parabola.",
        answer="ellipse",
        answer_display="ellipse",
        hint="x^2 and y^2 on the same side, both positive, equal to 1, is an ellipse.",
        common_mistakes=["Calling it a circle (the denominators 9 and 4 are different, so the axes have different lengths)."],
        exam_tags=["clep_precalc"],
        steps=S(
            ("Goal", "Recognize a conic from its equation."),
            ("Form", "Both variables are squared, added, and set equal to 1. That is the standard ellipse $\\frac{x^2}{a^2} + \\frac{y^2}{b^2} = 1$."),
            ("Not a circle", "a^2 = 9 and b^2 = 4 are different, so this is stretched, not a circle."),
            ("Not a hyperbola", "A hyperbola would have a minus between the two squared terms."),
        ),
    ),
    P(
        id="diag-4-3",
        skill_id="pc-10-3",
        stage=4,
        cluster="precalc",
        prompt="A point has polar coordinates $(r,\\theta) = (2, \\pi)$. What is its Cartesian x-coordinate?",
        answer="-2",
        answer_display="-2",
        hint="x = r cos θ.",
        common_mistakes=["Answering 2, forgetting that π points left on the polar axis."],
        exam_tags=["ap_precalc_u3"],
        steps=S(
            ("Goal", "Convert polar to Cartesian with x = r cos θ, y = r sin θ."),
            ("Angle π", "θ = π is the negative x-axis. cos π = -1 and sin π = 0."),
            ("Compute x", "x = r cos θ = 2 · cos(π) = 2 · (-1) = -2."),
            ("Picture", "The point is 2 units left of the origin: (-2, 0)."),
        ),
    ),
    P(
        id="diag-4-4",
        skill_id="alg-13-2",
        stage=4,
        cluster="precalc",
        prompt="An arithmetic sequence has a1 = 4 and d = 3. Find a_10.",
        answer="31",
        answer_display="31",
        hint="a_n = a1 + (n-1)d.",
        common_mistakes=["4 + 10·3 = 34, using n instead of n-1."],
        exam_tags=["clep_algebra", "ap_precalc_u2"],
        steps=S(
            ("Goal", "Find the 10th term of an arithmetic sequence."),
            ("Formula", "The nth term of an arithmetic sequence is a_n = a1 + (n-1)d."),
            ("Plug in", "a_10 = 4 + (10-1)·3 = 4 + 27 = 31."),
            ("Count jumps", "Nine jumps of 3 from the first term to the tenth."),
        ),
    ),
    P(
        id="diag-4-5",
        skill_id="alg-13-6",
        stage=4,
        cluster="precalc",
        prompt="What is the coefficient of $x^2 y^2$ in $(x+y)^4$?",
        answer="6",
        answer_display="6",
        hint="C(4,2) because you choose 2 of the 4 factors to contribute a y (the rest contribute x).",
        common_mistakes=["Answering 4, or 8."],
        exam_tags=["clep_algebra"],
        steps=S(
            ("Goal", "Read a coefficient from the binomial theorem."),
            ("General term", "(x+y)^4 includes C(4,k) x^{4-k} y^k. We want x^2 y^2, so k = 2."),
            ("Compute C(4,2)", "C(4,2) = 4! / (2! 2!) = 24 / 4 = 6."),
            ("Expand check", "(x+y)^4 = x^4 + 4x^3 y + 6 x^2 y^2 + 4 x y^3 + y^4."),
        ),
    ),
    P(
        id="diag-4-6",
        skill_id="pc-limit-2",
        stage=4,
        cluster="precalc",
        prompt="Evaluate $\\lim_{x \\to 3} \\dfrac{x^2 - 9}{x-3}$.",
        answer="6",
        answer_display="6",
        hint="Direct substitution gives 0/0. Factor the numerator and cancel, then substitute.",
        common_mistakes=["Saying the limit is 0, or that it does not exist because the function is undefined at 3."],
        exam_tags=["clep_precalc"],
        steps=S(
            ("Goal", "A limit asks what y approaches, not whether f(3) is defined."),
            ("Indeterminate plug-in", "Numerator 9-9=0, denominator 0. 0/0 means 'keep simplifying', not 'the limit is 0'."),
            ("Factor", "x^2-9 = (x-3)(x+3). Cancel x-3 for x ≠ 3, leaving x+3."),
            ("Now substitute", "lim_{x→3} (x+3) = 6. The original function has a hole at x=3; the limit still exists and equals 6."),
        ),
    ),
    P(
        id="diag-4-7",
        skill_id="pc-10-8",
        stage=4,
        cluster="precalc",
        prompt="Find the magnitude of the vector $\\langle 3, -4 \\rangle$.",
        answer="5",
        answer_display="5",
        hint="Magnitude is √(a^2 + b^2), the same formula as distance from the origin.",
        common_mistakes=["Answering 7 (adding 3+4) or -5."],
        exam_tags=["ap_precalc_u4"],
        steps=S(
            ("Goal", "Magnitude is the length of the arrow, always nonnegative."),
            ("Formula", "|⟨a,b⟩| = √(a^2 + b^2)."),
            ("Compute", "√(3^2 + (-4)^2) = √(9+16) = √25 = 5. Magnitude is never negative."),
            ("Picture", "This is a 3-4-5 right triangle. The minus on 4 affects direction, not length."),
        ),
    ),
    P(
        id="diag-4-8",
        skill_id="pc-11-5",
        stage=4,
        cluster="precalc",
        prompt="If $A = \\begin{bmatrix} 1 & 2 \\\\ 0 & 3 \\end{bmatrix}$, what is the entry in row 2, column 2?",
        answer="3",
        answer_display="3",
        hint="Rows across, columns down. Row 2 column 2 is the bottom-right entry here.",
        common_mistakes=["Reading 2 (row 1 col 2) or 0 (row 2 col 1)."],
        exam_tags=["ap_precalc_u4"],
        steps=S(
            ("Goal", "Matrix indexing is (row, column), with row 1 at the top and column 1 at the left."),
            ("Row 2", "The second row is [0  3]."),
            ("Column 2 of that row", "The second entry is 3."),
            ("Why this matters", "Later, multiplying matrices depends on matching row-of-first with column-of-second. Indexing has to be automatic."),
        ),
    ),
]
