from __future__ import annotations

import random
from dataclasses import dataclass

from src.identities import FIELD_LABEL, FIELD_ORDER, IDENTITIES

FAMILY_ORDER = (
    "algebra",
    "functions",
    "trig",
    "precalc",
    "kinematics",
    "forces",
    "energy",
    "momentum",
    "circular",
    "waves",
    "circuits",
    "fluids",
    "thermo",
    "em",
    "optics",
    "modern",
)
FAMILY_LABEL = {
    "algebra": "Algebra",
    "functions": "Functions & graphs",
    "trig": "Trig identities",
    "precalc": "Precalculus",
    "kinematics": "Kinematics",
    "forces": "Forces",
    "energy": "Energy & work",
    "momentum": "Momentum",
    "circular": "Rotation & gravity",
    "waves": "Oscillations & waves",
    "circuits": "Circuits",
    "fluids": "Fluids",
    "thermo": "Thermo",
    "em": "E & M",
    "optics": "Optics",
    "modern": "Modern physics",
}

_M = ("math",)
_MP = ("math", "physics")
_ME = ("math", "ee")
_MM = ("math", "me")
_MPE = ("math", "physics", "ee")
_MPM = ("math", "physics", "me")
_ALL = ("math", "physics", "ee", "me")
_P = ("physics",)
_PE = ("physics", "ee")
_PM = ("physics", "me")
_PEM = ("physics", "ee", "me")
_E = ("ee",)
_EM = ("ee", "me")


@dataclass(frozen=True)
class Flashcard:
    id: str
    family: str
    name: str
    front: str
    back_tex: str
    fields: tuple[str, ...]
    why: str

    @property
    def family_label(self) -> str:
        return FAMILY_LABEL[self.family]

    def field_labels(self) -> tuple[str, ...]:
        return tuple(FIELD_LABEL[f] for f in FIELD_ORDER if f in self.fields)


def _c(
    card_id: str,
    family: str,
    name: str,
    front: str,
    back_tex: str,
    fields: tuple[str, ...],
    why: str,
) -> Flashcard:
    return Flashcard(card_id, family, name, front, back_tex, fields, why)


FORMULAS: tuple[Flashcard, ...] = (
    _c("alg-slope-int", "algebra", "Slope-intercept line",
       "Equation of a line with slope m and y-intercept b",
       r"y = mx + b",
       _ALL, "The default linear model: constant rate m, starting value b."),
    _c("alg-slope", "algebra", "Slope between two points",
       "Slope m through (x₁, y₁) and (x₂, y₂)",
       r"m = \dfrac{y_2 - y_1}{x_2 - x_1}",
       _ALL, "Rise over run. Same number as the average rate of change of a line."),
    _c("alg-point-slope", "algebra", "Point-slope form",
       "Line of slope m through (x₁, y₁)",
       r"y - y_1 = m(x - x_1)",
       _M, "Often the fastest way to write a tangent line in Calc 1."),
    _c("alg-distance", "algebra", "Distance formula",
       "Distance between (x₁, y₁) and (x₂, y₂)",
       r"d = \sqrt{(x_2-x_1)^2 + (y_2-y_1)^2}",
       _MPM, "Pythagoras in the coordinate plane. Same idea as a vector magnitude."),
    _c("alg-midpoint", "algebra", "Midpoint",
       "Midpoint of the segment from (x₁, y₁) to (x₂, y₂)",
       r"\left(\dfrac{x_1+x_2}{2},\;\dfrac{y_1+y_2}{2}\right)",
       _M, "Average the coordinates. Not a distance."),
    _c("alg-pythag", "algebra", "Pythagorean theorem",
       "Right triangle with legs a, b and hypotenuse c",
       r"a^2 + b^2 = c^2",
       _ALL, "Distance, magnitude, and the identity behind sin² + cos² = 1."),
    _c("alg-quad", "algebra", "Quadratic formula",
       "Solutions of ax² + bx + c = 0",
       r"x = \dfrac{-b \pm \sqrt{b^2 - 4ac}}{2a}",
       _MP, "When factoring stalls. Discriminant b² − 4ac tells how many real roots."),
    _c("alg-disc", "algebra", "Discriminant",
       "Number of real roots of ax² + bx + c = 0",
       r"\Delta = b^2 - 4ac",
       _M, "Positive: two real. Zero: one. Negative: none (in the reals)."),
    _c("alg-exp-prod", "algebra", "Product of powers",
       "Same base, multiply",
       r"a^m a^n = a^{m+n}",
       _ALL, "Add exponents. The log rule log u + log v is the same idea."),
    _c("alg-exp-pow", "algebra", "Power of a power",
       "Raise a power to another power",
       r"(a^m)^n = a^{mn}",
       _ALL, "Multiply exponents. Shows up in (e^{kt})^n and in log laws."),
    _c("alg-exp-quot", "algebra", "Quotient of powers",
       "Same base, divide",
       r"\dfrac{a^m}{a^n} = a^{m-n}",
       _M, "Subtract exponents. a⁰ = 1 when a ≠ 0."),
    _c("alg-log-def", "algebra", "Logarithm definition",
       "What log_b a means",
       r"\log_b a = c \iff b^c = a",
       _MPE, "A log is an exponent. The question is 'b to what power is a?'"),
    _c("alg-log-sum", "algebra", "Log of a product",
       "log_b (uv)",
       r"\log_b(uv) = \log_b u + \log_b v",
       _ME, "Turns multiplication into addition — how you expand log models."),
    _c("alg-log-quot", "algebra", "Log of a quotient",
       "log_b (u/v)",
       r"\log_b(u/v) = \log_b u - \log_b v",
       _ME, "Turns division into subtraction."),
    _c("alg-log-pow", "algebra", "Log of a power",
       "log_b (u^k)",
       r"\log_b(u^k) = k\log_b u",
       _MPE, "Brings the exponent out front. Core of exponential decay algebra."),
    _c("alg-change-base", "algebra", "Change of base",
       "log_b a in a calculator base",
       r"\log_b a = \dfrac{\log a}{\log b} = \dfrac{\ln a}{\ln b}",
       _ME, "Any log is a ratio of logs. Calculators only have log and ln."),
    _c("alg-direct", "algebra", "Direct variation",
       "y varies directly with x",
       r"y = kx",
       _M, "Proportional. The graph is a line through the origin."),
    _c("alg-inverse-var", "algebra", "Inverse variation",
       "y varies inversely with x",
       r"y = \dfrac{k}{x}",
       _MM, "Hyperbola. Twice the x means half the y."),
    _c("alg-abs", "algebra", "Absolute value",
       "What |a| means",
       r"|a| = \text{distance from }a\text{ to }0",
       _M, "Never negative. |a| = a if a ≥ 0 and −a if a < 0."),
    _c("alg-arith-term", "algebra", "Arithmetic nth term",
       "Term n of an arithmetic sequence",
       r"a_n = a_1 + (n-1)d",
       _M, "Add the common difference once for every step after the first term."),
    _c("alg-arith-sum", "algebra", "Arithmetic series",
       "Sum of the first n arithmetic terms",
       r"S_n = \dfrac{n}{2}(a_1 + a_n)",
       _M, "n times the average of the first and last terms."),
    _c("alg-geo-term", "algebra", "Geometric nth term",
       "Term n of a geometric sequence",
       r"a_n = a_1 r^{n-1}",
       _ME, "Multiply by r at every step. First term already uses exponent 0."),
    _c("alg-geo-sum", "algebra", "Finite geometric series",
       "Sum of the first n geometric terms (r ≠ 1)",
       r"S_n = a_1\dfrac{1-r^n}{1-r}",
       _ME, "The closed form behind repeating decimals and some discrete EE sums."),
    _c("fn-vertex", "functions", "Parabola vertex (x)",
       "x-coordinate of the vertex of y = ax² + bx + c",
       r"x = -\dfrac{b}{2a}",
       _MP, "Axis of symmetry. Then plug back in to get the y of the turning point."),
    _c("fn-vertex-form", "functions", "Vertex form",
       "Parabola with vertex (h, k)",
       r"y = a(x-h)^2 + k",
       _M, "a stretches; (h, k) is the vertex. Minus inside means shift right."),
    _c("fn-comp", "functions", "Composition",
       "(f ∘ g)(x)",
       r"(f\circ g)(x) = f(g(x))",
       _ALL, "Inside first. Not multiplication of f and g."),
    _c("fn-roc", "functions", "Average rate of change",
       "Average rate of change of f from a to b",
       r"\dfrac{f(b)-f(a)}{b-a}",
       _ALL, "Secant slope. The derivative is this with b → a."),
    _c("fn-period", "functions", "Sine/cosine period",
       "Period of y = A sin(bx) or A cos(bx)",
       r"T = \dfrac{2\pi}{|b|}",
       _ALL, "How far x must move for one full wave. Tangent uses π/|b| instead."),
    _c("fn-amp", "functions", "Amplitude",
       "Amplitude of y = A sin(bx) + k",
       r"|A|",
       _ALL, "Height from midline to peak. Never negative."),
    _c("fn-midline", "functions", "Midline of a sinusoid",
       "Midline of y = A sin(bx) + k",
       r"y = k",
       _MP, "The horizontal axis the wave oscillates around."),
    _c("fn-tan-period", "functions", "Tangent period",
       "Period of y = tan(bx)",
       r"T = \dfrac{\pi}{|b|}",
       _M, "Parent tangent repeats every π, not 2π. Cotangent uses the same period."),
    _c("fn-cot-period", "functions", "Cotangent period",
       "Period of y = cot(bx)",
       r"T = \dfrac{\pi}{|b|}",
       _M, "Parent cotangent repeats every π, same as tangent: cot(θ + πn) = cot(θ)."),
    _c("fn-va", "functions", "Vertical asymptote",
       "Vertical asymptote of a simplified rational f = p/q",
       r"q(x)=0\text{ and }p(x)\neq 0",
       _M, "A hole is a cancelled factor. A VA is a factor that survives."),
    _c("pc-polar-x", "precalc", "Polar to Cartesian x",
       "x from polar (r, θ)",
       r"x = r\cos\theta",
       _MPE, "The adjacent / cosine projection from the pole."),
    _c("pc-polar-y", "precalc", "Polar to Cartesian y",
       "y from polar (r, θ)",
       r"y = r\sin\theta",
       _MPE, "The opposite / sine projection from the pole."),
    _c("pc-mod", "precalc", "Complex modulus",
       "Magnitude of a + bi",
       r"|a+bi| = \sqrt{a^2+b^2}",
       _ME, "Distance from 0 in the complex plane. Same as a vector length."),
    _c("pc-ellipse", "precalc", "Ellipse (standard)",
       "Axis-aligned ellipse centered at the origin",
       r"\dfrac{x^2}{a^2} + \dfrac{y^2}{b^2} = 1",
       _M, "Vertices at (±a, 0) and (0, ±b). Take square roots of the denominators."),
    _c("pc-hyperbola", "precalc", "Hyperbola (opens left-right)",
       "Which form opens left-right",
       r"\dfrac{x^2}{a^2} - \dfrac{y^2}{b^2} = 1",
       _M, "The plus side is the transverse axis. x² first means left-right."),
    _c("pc-parab-focus", "precalc", "Parabola focus",
       "Focus of y = x² / (4p) with vertex at the origin",
       r"(0, p)",
       _MM, "Equal distance to focus and directrix y = −p. Mirrors and cables."),
    _c("pc-ecc", "precalc", "Eccentricity",
       "Conic from eccentricity e",
       r"e<1\text{ ellipse},\; e=1\text{ parabola},\; e>1\text{ hyperbola}",
       _M, "A circle is e = 0. Polar form r = ed / (1 − e cos θ) uses the same e."),
    _c("kin-g", "kinematics", "g in this course",
       "Gravitational field strength used in every in-app physics problem",
       r"g = 10\,\mathrm{m/s^2}",
       _PEM, "Algebra-based AP Physics 1 & 2. The prompt will say g = 10 when gravity appears."),
    _c("kin-vavg", "kinematics", "Average velocity",
       "Average velocity on a straight line",
       r"v_{\mathrm{avg}} = \dfrac{\Delta x}{\Delta t}",
       _PM, "Displacement over time, including sign. Not path length over time."),
    _c("kin-v", "kinematics", "Velocity with constant a",
       "Final velocity after constant acceleration",
       r"v = v_0 + at",
       _PEM, "Each second adds a meters per second."),
    _c("kin-x", "kinematics", "Position with constant a",
       "Displacement with constant acceleration",
       r"\Delta x = v_0 t + \tfrac12 at^2",
       _PM, "The area under a v–t graph. Dropped from rest means v₀ = 0."),
    _c("kin-v2", "kinematics", "Timeless kinematics",
       "When time is missing (constant a)",
       r"v^2 = v_0^2 + 2a\Delta x",
       _PM, "Use this when the question gives distances, not times."),
    _c("kin-drop", "kinematics", "Free-fall distance from rest",
       "Dropped from rest, down positive, constant g",
       r"\Delta y = \tfrac12 g t^2",
       _PM, "v₀ = 0. In this app g = 10 m/s²."),
    _c("kin-range45", "kinematics", "Range at 45°",
       "Level-ground range at 45° (no air)",
       r"R = \dfrac{v^2}{g}",
       _PM, "Because sin 90° = 1 in R = v² sin(2θ)/g."),
    _c("f-n2", "forces", "Newton’s second law",
       "Net force and acceleration",
       r"\Sigma F = ma",
       _PEM, "a is caused by the net force, not by 'being in motion'."),
    _c("f-weight", "forces", "Weight",
       "Gravitational force on a mass",
       r"W = mg",
       _PEM, "Weight is a force in newtons. Mass is kilograms."),
    _c("f-fk", "forces", "Kinetic friction",
       "Sliding friction magnitude",
       r"f_k = \mu_k N",
       _PM, "N is the normal force, which is not always mg."),
    _c("f-fsmax", "forces", "Max static friction",
       "Largest static friction before slip",
       r"f_{s,\max} = \mu_s N",
       _PM, "Static friction can be anything from 0 up to this ceiling."),
    _c("en-work", "energy", "Work by a constant force",
       "Work when F is constant",
       r"W = Fd\cos\theta",
       _PM, "θ = 0° along the motion gives W = Fd. Joules are N·m."),
    _c("en-ke", "energy", "Kinetic energy",
       "Translational kinetic energy",
       r"K = \tfrac12 mv^2",
       _PEM, "Square the speed first. Twice the speed is four times the K."),
    _c("en-pe", "energy", "Gravitational PE near Earth",
       "Change in gravitational potential energy",
       r"U = mgh",
       _PM, "h is height above a chosen zero. Only ΔU matters."),
    _c("en-cons", "energy", "Mechanical energy (no friction)",
       "Conservation of mechanical energy",
       r"K_i + U_i = K_f + U_f",
       _PM, "On a frictionless ramp, mgh at the top becomes ½mv² at the bottom."),
    _c("en-power", "energy", "Average power",
       "Average power",
       r"P = \dfrac{W}{t} = Fv",
       _PEM, "Watts are J/s. The Fv form is for force along the velocity."),
    _c("mom-p", "momentum", "Momentum",
       "Linear momentum",
       r"p = mv",
       _PEM, "A vector. Impulse is how much p changes."),
    _c("mom-j", "momentum", "Impulse",
       "Impulse of a constant net force",
       r"J = F\Delta t = \Delta p",
       _PM, "Same units as momentum: N·s = kg·m/s."),
    _c("mom-cons", "momentum", "Momentum conservation",
       "No external impulse, two objects",
       r"m_1 v_{1i} + m_2 v_{2i} = m_1 v_{1f} + m_2 v_{2f}",
       _PM, "Sticking is inelastic: one v after, KE is not conserved."),
    _c("cir-ac", "circular", "Centripetal acceleration",
       "Center-pointing acceleration at constant speed",
       r"a_c = \dfrac{v^2}{r}",
       _PEM, "Direction changes, so there is acceleration even at constant speed."),
    _c("cir-fc", "circular", "Centripetal force",
       "Net force toward the center",
       r"F_c = \dfrac{mv^2}{r}",
       _PM, "Not a new kind of force — it is the name for ΣF_inward."),
    _c("cir-g", "circular", "Surface gravity",
       "g from Newton’s law of gravity",
       r"g = \dfrac{GM}{R^2}",
       _PM, "Same mass and twice the radius → g is 1/4 as large."),
    _c("cir-fg", "circular", "Newton’s gravity",
       "Force between two point masses",
       r"F = G\dfrac{m_1 m_2}{r^2}",
       _PM, "Always attractive. r is center-to-center."),
    _c("cir-tau", "circular", "Torque",
       "Torque of a force about a pivot",
       r"\tau = rF\sin\theta",
       _PM, "Perpendicular force means sin 90° = 1, so τ = rF."),
    _c("wav-shm", "waves", "Mass-spring period",
       "Period of a mass on a spring",
       r"T = 2\pi\sqrt{\dfrac{m}{k}}",
       _PM, "Amplitude does not appear. Upside-down (k/m) is the wrong formula."),
    _c("wav-pend", "waves", "Simple pendulum (small angle)",
       "Period of a simple pendulum",
       r"T = 2\pi\sqrt{\dfrac{L}{g}}",
       _PM, "Small-angle SHM. Mass cancels."),
    _c("wav-v", "waves", "Wave speed",
       "Speed of a periodic wave",
       r"v = f\lambda",
       _PEM, "Frequency in Hz times wavelength. Holds for sound, light, and string waves."),
    _c("wav-f", "waves", "Frequency and period",
       "Frequency from period",
       r"f = \dfrac{1}{T}",
       _ALL, "Cycles per second. Angular frequency ω = 2πf."),
    _c("wav-omega", "waves", "Angular frequency",
       "ω for SHM or a sinusoid in time",
       r"\omega = 2\pi f = \dfrac{2\pi}{T}",
       _ALL, "The coefficient of t in sin(ωt). Period is 2π/ω."),
    _c("ckt-ohm", "circuits", "Ohm’s law",
       "Current through a resistor",
       r"I = \dfrac{V}{R}",
       _PE, "Amperes when V is volts and R is ohms."),
    _c("ckt-p", "circuits", "Electric power",
       "Power in a circuit element",
       r"P = IV = I^2 R = \dfrac{V^2}{R}",
       _PE, "Watts. P = I²R is handy for a known current in a resistor."),
    _c("ckt-series", "circuits", "Series resistors",
       "Equivalent of series resistors",
       r"R_{\mathrm{eq}} = R_1 + R_2 + \cdots",
       _PE, "Same current. R_eq is larger than each piece."),
    _c("ckt-par", "circuits", "Parallel resistors",
       "Equivalent of two parallel resistors",
       r"\dfrac{1}{R_{\mathrm{eq}}} = \dfrac{1}{R_1} + \dfrac{1}{R_2}",
       _PE, "R_eq is smaller than either branch. Two equal R’s in parallel → R/2."),
    _c("ckt-q", "circuits", "Charge and current",
       "Current as charge flow",
       r"I = \dfrac{\Delta q}{\Delta t}",
       _PE, "An ampere is a coulomb per second."),
    _c("fl-p", "fluids", "Pressure",
       "Pressure from a force on an area",
       r"P = \dfrac{F}{A}",
       _PM, "Pascals are newtons per square meter. Same force on a smaller area is more pressure."),
    _c("fl-hydro", "fluids", "Hydrostatic pressure",
       "Extra pressure at depth h in a fluid",
       r"P = P_0 + \rho g h",
       _PM, "Depends on depth, not on the shape of the container."),
    _c("fl-buoy", "fluids", "Archimedes",
       "Buoyant force",
       r"F_b = \rho_{\mathrm{fluid}} V_{\mathrm{disp}} g",
       _PM, "Weight of the displaced fluid. Fully under → V_disp = V_object."),
    _c("fl-cont", "fluids", "Continuity",
       "Incompressible flow in a pipe",
       r"A_1 v_1 = A_2 v_2",
       _PM, "Narrower means faster. Volume per second is conserved."),
    _c("th-ideal", "thermo", "Ideal gas law",
       "Ideal gas",
       r"PV = nRT",
       _P, "Use Kelvin. At fixed n and V, P is proportional to T."),
    _c("th-first", "thermo", "First law (W by the gas)",
       "First law with W = work by the system",
       r"\Delta U = Q - W",
       _P, "Heat in is positive Q. Expanding gas does positive W."),
    _c("em-coulomb", "em", "Coulomb’s law",
       "Force between two point charges",
       r"F = k\dfrac{|q_1 q_2|}{r^2}",
       _PE, "k = 9.0×10⁹ N·m²/C². Convert μC to C first."),
    _c("em-e", "em", "Electric field and force",
       "Force on a charge in a field E",
       r"F = qE",
       _PE, "N/C already means newtons per coulomb. With E for a positive q."),
    _c("em-fb", "em", "Magnetic force on a charge",
       "Magnetic force (constant B)",
       r"F = qvB\sin\theta",
       _PE, "Perpendicular v and B → sin 90° = 1. Parallel → zero."),
    _c("op-snell", "optics", "Snell’s law",
       "Refraction at a boundary",
       r"n_1\sin\theta_1 = n_2\sin\theta_2",
       _P, "Angles are from the normal. Larger n → smaller θ."),
    _c("op-lens", "optics", "Thin-lens equation",
       "Thin lens (or spherical mirror)",
       r"\dfrac{1}{f} = \dfrac{1}{d_o} + \dfrac{1}{d_i}",
       _P, "Solve for d_i. Positive d_i is a real image for a converging lens."),
    _c("op-m", "optics", "Lateral magnification",
       "Magnification from image and object distance",
       r"m = -\dfrac{d_i}{d_o} = \dfrac{h_i}{h_o}",
       _P, "Negative m means an inverted image."),
    _c("mod-e", "modern", "Photon energy (eV shortcut)",
       "Photon energy with λ in nanometers",
       r"E(\mathrm{eV}) = \dfrac{1240}{\lambda(\mathrm{nm})}",
       _PE, "This is E = hc/λ with hc packaged as 1240 eV·nm."),
    _c("mod-photo", "modern", "Photoelectric equation",
       "Max KE of a photoelectron",
       r"K_{\max} = hf - \phi",
       _PE, "Threshold is when hf = φ. Below that, no electrons."),
)


def _from_identity(item) -> Flashcard:
    return Flashcard(
        id=f"id-{item.id}",
        family="trig",
        name=item.name,
        front=item.lhs_html,
        back_tex=item.rhs_tex,
        fields=item.fields,
        why=item.why,
    )


def all_flashcards() -> tuple[Flashcard, ...]:
    trig = tuple(_from_identity(item) for item in IDENTITIES)
    return FORMULAS + trig


def flashcards_for(*, field: str = "all", family: str = "all") -> tuple[Flashcard, ...]:
    rows = all_flashcards()
    if field != "all":
        rows = tuple(card for card in rows if field in card.fields)
    if family != "all":
        rows = tuple(card for card in rows if card.family == family)
    return rows


def shuffled_ids(cards: tuple[Flashcard, ...], seed: int | None = None) -> list[str]:
    ids = [card.id for card in cards]
    rng = random.Random(seed)
    rng.shuffle(ids)
    return ids
